# Generated by Django 4.1.7 on 2023-02-16 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterpackages',
            old_name='img_path',
            new_name='max_altitude',
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='main_image',
            field=models.ImageField(default='', upload_to='main_images'),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_agegroup',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_desc',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_difficulty',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_duration',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='masterpackages',
            name='package_price',
            field=models.IntegerField(default=0),
        ),
    ]
