# Generated by Django 4.1.7 on 2023-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0005_review_reviewer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdata',
            old_name='customer_name',
            new_name='customer_fname',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='customer_lname',
            field=models.TextField(default='', max_length=100),
        ),
    ]
