# Generated by Django 4.1.7 on 2023-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_rename_customer_name_customerdata_customer_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer_fname',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='customer_lname',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
