# Generated by Django 4.1.7 on 2023-02-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_alter_customerdata_customer_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
