# Generated by Django 4.1.7 on 2023-02-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0008_review_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpackages',
            name='package_detail',
            field=models.TextField(default='', max_length=100),
        ),
    ]
